### ISSUE TITLE
Change the Configuration Schema of 'trident' to the one used for 'harbor'

### ISSUE THREAD

**Issue by gprossliner** [world-direct/k8s-setup#44]
The trident Configuration Schema was designed without nesting:

```yaml
## Trident information
#############################################################

# this specifes the version of trident to be installed.
# If this is left blank, trident will not be installed.
trident_version: ""
trident_backend_config:
  version: 1
  storageDriverName: ontap-nas
  ....
```

The harbor Schema is easier to read:
```yaml
 ## Harbor information
#############################################################

# this specifes the version of harbor to be installed
# If this is left blank, harbor will not be installed.
harbor:
  enabled: yes
  version: 1.9.3
  enable_persistence: no
  admin_password: Harbor12345
  secret_key: not-a-secure-key
```

We should migrate to the nested format.
