### ISSUE TITLE
Restructure configuration schema, including default-combining

### ISSUE THREAD

**Issue by gprossliner** [world-direct/k8s-setup#47]
On beta1 we should have a consistent configuration schema, see also #44. This should include applying defaults for dictionaries, so that we can provide defaults in one level deep, like:

```yaml
# defaults.yml
harbor:
  enabled: no
  version: 1.9.3

# instance-specific.yml
harbor:
  enabled: yes

# this should merge to
harbor:
  enabled: yes
  version: 1.9.3

```

See: https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#combining-hashes-dictionaries
