### ISSUE TITLE
/etc/ansible/hosts path handling

### ISSUE THREAD

**Issue by flo-weber** [world-direct/k8s-setup#64]
Ansible hosts file should be integrated in the provisioning and able to load from private repo

**Comment by gprossliner** [comment]
It was already possible to specify the path to the ansible inventory file.

This fix implements a better handling of relative paths, so that they are considered relative to the file that contains the 'ansible_inventory_filepath' setting.

This allows the configuration to be pulled from it's own repository ('configrepo'), and using just relative and "self-containing" paths, like:

```yaml
# configrepo/customconfig.yaml
ansible_inventory_filepath: ./hosts.yaml

# configrepo/hosts.yaml
# This is the ansible inventory file
all:
   hosts:
      ...
```
