### ISSUE TITLE
http to https forwarding

### ISSUE THREAD

**Issue by flo-weber** [world-direct/k8s-setup#90]
For HTTPS only sites there should be an option for http to https forwarding

**Comment by flo-weber** [comment]
Can be set with the ingress annotation nginx.ingress.kubernetes.io/ssl-passthrough: 'true'

```yaml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: kubernetes-dashboard
  namespace: kube-dashboard
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
```
