### ISSUE TITLE
habor ignoriert tls enabled true

### ISSUE THREAD

**Issue by flo-weber** [world-direct/k8s-setup#91]
The tls: enabled in the values.yaml is 

values.yaml
```yaml
expose:
  # Set the way how to expose the service. Set the type as "ingress",
  # "clusterIP", "nodePort" or "loadBalancer" and fill the information
  # in the corresponding section
  type: ingress
  tls:
    # Enable the tls or not. Note: if the type is "ingress" and the tls
    # is disabled, the port must be included in the command when pull/push
    # images. Refer to https://github.com/goharbor/harbor/issues/5291
    # for the detail.
    enabled: true
```

ingress.yaml
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "harbor.ingress" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
spec:
  {{- if $tls.enabled }}
  tls:
    {{- if $tls.secretName }}
  - secretName: {{ $tls.secretName }}
    {{- else }}
  - secretName: "{{ template "harbor.ingress" . }}"
    {{- end }}
    {{- if $ingress.hosts.core }}
    hosts:
    - {{ $ingress.hosts.core }}
    {{- end }}
  {{- if .Values.notary.enabled }}
    {{- if $tls.notarySecretName }}
  - secretName: {{ $tls.notarySecretName }}
    {{- else if $tls.secretName }}
  - secretName: {{ $tls.secretName }}
    {{- else }}
  - secretName: "{{ template "harbor.ingress" . }}"
    {{- end }}
    {{- if $ingress.hosts.notary }}
    hosts:
    - {{ $ingress.hosts.notary }}
    {{- end }}
  {{- end }}
  {{- end }}
```

active ingress:
```yaml
spec:
  rules:
    - host: harbor.cluster.local
      http:
        paths:
          - path: /
            backend:
              serviceName: harbor-harbor-portal
              servicePort: 80
          - path: /api/
            backend:
              serviceName: harbor-harbor-core
              servicePort: 80
          - path: /service/
            backend:
              serviceName: harbor-harbor-core
              servicePort: 80
          - path: /v2/
            backend:
              serviceName: harbor-harbor-core
              servicePort: 80
          - path: /chartrepo/
            backend:
              serviceName: harbor-harbor-core
              servicePort: 80
          - path: /c/
            backend:
              serviceName: harbor-harbor-core
              servicePort: 80
```

the tls block is missing
